### ISSUE TITLE
stalonetray.1 has some format errors in Arch's package

### ISSUE THREAD

**Issue by OliverLew** [kolbusa/stalonetray#7]
First the error is the same in Arch's official package and on my local machine. But I am not sure if it's only in Arch Linux, if the issue can not be reproduced elsewhere, then it's probably due to arch's [PKGBUILD](https://github.com/archlinux/svntogit-community/blob/packages/stalonetray/trunk/PKGBUILD) or dependency package version.
Since none of the `DOCBOOK_ROOT` candidate locations exists in Arch, the PKGBUILD replaced one with another directory belonging to [docbook-xsl](https://archlinux.org/packages/extra/any/docbook-xsl/). This seems the only change made in Arch's package.

The manual within the package from Arch's offcial repository has some errors when viewing with `man`:
```
         .PP Default configuration file is $HOME/.stalonetrayrc. If it is not
       found, then $XDG_CONFIG_HOME/stalonetrayrc is checked for. A
       configuration file contains case-insensetive keyword-argument pairs,
       one per line. Lines starting with '#' and empty lines are ignored.
       Alternatively, confiuration file can specified via -c or --config
       command-line options.

         .PP Below is the list of possible command line/configuration file
       options. Options starting with hyphens are command-line parameters
       others are configuration file keywords. Options that are new in 0.8
       version are marked with "NEW in 0.8".

OPTIONS
         .PP -bg color, --background color, background color

             Use color for tray`s background.  color can be specified as an
           HTML hex triplet or as a name from rgb.txt (note that '#' must be
           quoted). Default value: #777777.

             .RE

             .PP -c filename, --config filename

                 Read configuration from filename instead of default
               $HOME/.stalonetrayrc.

                 .RE

                 .PP -d decspec, --decorations decspec, decorations decspec

                     Specify visiblie tray window decorations. Possible values
                   for decspec are: all, title, border, none (default).

                     .RE

                     .PP -display display, display display
```
The reason is those `.PP`, `.RE`, etc. has spaces in front of them in the generated `stalonetray.1`:
```man
.SH "OPTIONS"

  

  


  .PP
\fB\-bg\fR \fIcolor\fR, \fB\-\-background\fR \fIcolor\fR, \fBbackground\fR \fIcolor\fR
.RS 4

  
  
  
  Use
\fIcolor\fR
for tray`s background\&.
\fIcolor\fR
can be specified as an
HTML
hex triplet or as a name from rgb\&.txt (note that \*(Aq#\*(Aq must be quoted)\&. Default value:
\fB#777777\fR\&.

  .RE
```

**Comment by kolbusa** [comment]
Thanks for the report. I currently don't have access to an Arch installation, and I don't see this issue on my Ubuntu box... I see that my Ubuntu install has docbook-xsl 1.79.1 and the link above shows that Arch has 1.79.2. Maybe that is the reason. I'll get back to this when I have a bit more time on my hands. A PR that fixes this (and adds the Arch install path to `configure.ac`) would be very welcome.

**Comment by 0** [comment]
The cause appears to be that DocBook 5 supports namespaces, while version 4 didn't, and distributions handle this differently. Ubuntu has two packages:

* `docbook-xsl` puts the DB4 stylesheets in `/usr/share/xml/docbook/stylesheet/docbook-xsl/`
* `docbook-xsl-ns` puts the DB5 stylesheets in `/usr/share/xml/docbook/stylesheet/docbook-xsl-ns/`

Arch has one package for both:

* `docbook-xsl` puts the DB4 stylesheets in `/usr/share/xml/docbook/xsl-stylesheets-1.79.2-nons/`
* `docbook-xsl` puts the DB5 stylesheets in `/usr/share/xml/docbook/xsl-stylesheets-1.79.2/`

Note that the former considers the DB4 (non-ns) stylesheets to be the default, and the latter the DB5 (ns) ones.

Using `xsl-stylesheets-1.79.2-nons/manpages/docbook.xsl` instead of `xsl-stylesheets-1.79.2/manpages/docbook.xsl` fixes the whitespace in the generated file.

Reference: https://lists.oasis-open.org/archives/docbook-apps/201810/msg00055.html

**Comment by ResonanceForge** [comment]
This issue ought to be reopened. The problem is here again.

Right now it uses `/usr/share/xml/docbook/xsl-stylesheets/manpages/docbook.xsl` on Arch.
